title: Tiana Lin
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2523251
  brandStrength: 0.5354457
  lightness: 0.2035446
  brandColors:
    - '#FFFFFF'
    - '#2D2D2E'
    - '#C1C1C1'
    - '#737373'
    - '#0057FB'
  rhythmicContrast: 0.3283408
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: tiana999
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4495167
layout_spectrum: 0.7077117417939007
