name: tiana999
favicon: null
layout_spectrum: 0.7077117417939007
typography_spectrum: 0.8880000670906156
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5683879968710244
  lightness: 0.03895002184435725
  saturation: 0.2523250631056726
  rhythmicContrast: 0.32834075717255473
purpose: []
